"""
Version and build metadata for Dad Ware.

VERSION is a hand-set constant, bumped deliberately by a developer when it's
time for a new release.

BUILD identifies the specific build/commit and is resolved automatically, in
priority order:

    1. A build stamp baked in at packaging time (utils/_build_stamp.py).
       This file is generated by build_executable.sh right before PyInstaller
       runs (there's no .git directory inside a frozen app to derive from),
       and is removed again afterwards. It is gitignored - it should never
       be committed, and never exists in a normal checkout.
    2. If running from a git checkout (not frozen), the latest commit's date
       and short hash, e.g. "2026-08-15-ecc32f4", with a "-dirty" suffix if
       the working tree has uncommitted changes.
    3. A literal fallback constant, so BUILD is always a non-empty string.

Frozen (PyInstaller) builds never shell out to git - there's no repository to
query, and spawning a subprocess from a bundled app for no reason is pure
latency. They rely entirely on the baked-in stamp, falling back to the
literal constant if, for whatever reason, the stamp is missing.
"""

import os
import subprocess
import sys

# Hand-set. Bump this deliberately when cutting a release.
VERSION = "0.1-poc"

# Used when neither a build stamp nor a git checkout is available.
_FALLBACK_BUILD = "unknown"

# Keep this short - it's on the startup path and must never make the CLI
# feel slow, especially since most invocations aren't even in a checkout.
_GIT_TIMEOUT_SECONDS = 2


def _project_root():
    """Directory containing the utils/ package (i.e. the project root)."""
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _build_from_git():
    """
    Derive a build string from the latest git commit, e.g. "2026-08-15-ecc32f4".
    Appends "-dirty" if the working tree has uncommitted changes.

    Swallows every failure (git missing, not a repo, timeout, non-zero exit)
    and returns None in that case - this must never raise.
    """
    root = _project_root()

    try:
        log_result = subprocess.run(
            ['git', 'log', '-1', '--date=format:%Y-%m-%d', '--format=%cd-%h'],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=_GIT_TIMEOUT_SECONDS,
        )
    except Exception:
        return None

    if log_result.returncode != 0:
        return None

    build = log_result.stdout.strip()
    if not build:
        return None

    try:
        status_result = subprocess.run(
            ['git', 'status', '--porcelain'],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=_GIT_TIMEOUT_SECONDS,
        )
        if status_result.returncode == 0 and status_result.stdout.strip():
            build += '-dirty'
    except Exception:
        # Dirty-state detection is best-effort; a clean build string without
        # the suffix is still a perfectly good answer.
        pass

    return build


def get_build():
    """
    Resolve the BUILD string. See module docstring for the priority order.

    Never raises, and never returns None or an empty string.
    """
    try:
        from utils._build_stamp import BUILD as _stamped_build
        if _stamped_build:
            return _stamped_build
    except ImportError:
        pass

    # No baked-in stamp. If we're a frozen (PyInstaller) app there's no git
    # repo to query, so don't even try - go straight to the fallback.
    if not getattr(sys, 'frozen', False):
        build = _build_from_git()
        if build:
            return build

    return _FALLBACK_BUILD


# Resolved once at import time for convenience, matching how VERSION is used
# elsewhere (e.g. `from utils.version import VERSION, BUILD`).
BUILD = get_build()
